/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //tests.testCase01();
        //END Tests
        //tests.endTest(); // End your test by clearning connections and closing browser

        //TODO: call your test case functions one after other here

        //AmazonSearch()
        // AmazonPage tests = new AmazonPage();
        // tests.searchAmazon();
        // tests.endTest();

        //BookMyShow
        // BookMyShow tests = new BookMyShow();
        // tests.hyperLink();
        // tests.endTest();

        // //LinkedIn
        // LinkedIn tests = new LinkedIn();
        // tests.getCount();
        // tests.endTest();

        //NestedFrames
        //   NestedFrames tests = new NestedFrames();
        //   tests.frames();
        //   //Thread.sleep();
        //   tests.endTest();

            //IMDB
        //    IMDB tests = new IMDB();
        //     tests.Rating();
           
        //     tests.endTest();

        //WindowHandle 
           WindowHandle tests = new WindowHandle();
            tests.Handle();
            //captureFullPageScreenshot();
            tests.endTest();
   
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}